### PR TITLE
Feature/2727 ng13

### LINKED ISSUE #275: Storybook build error
#### Describe the bug
Running "yarn start:storybook" throws errors in the terminal after linking components.

Error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs'
ERR! Require stack:
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_utils.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_config.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/presets.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/config.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/build-static.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/server.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/index.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_utils.js:19:25)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_config.js:29:27)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)

#### What is the expected behavior?
Run without error and warning
#### What are the steps to reproduce?
1. yarn start:storybook
2. view output in terminal

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #275 I'm putting this in because if we're not longer building storybook, then there can't be any errors, right? 

#### Changes proposed in this Pull Request:
- Migrate over to angular 13
- Preserve storybook in a working state at angular 12 w/ @brightlayer-ui/angular-components@6.0.3

#### To Test:
- Make sure you're on the showcase feature/ng13 branch, then run: 
- `yarn start:showcase`

### CODE REVIEW

**Comment by jeffvg** [comment]
noticing odd behavior with drawer with footer story. Clicking down the the hierarchy of stories and reaching the "with a footer" story the drawer doesn't display and throws error....

image

then clicking full config story then back up to the with footer story, the drawer displays

**Comment by jeffvg** [comment]
> noticing odd behavior with drawer with footer story. Clicking down the the hierarchy of stories and reaching the "with a footer" story the drawer doesn't display and throws error....
> 
> image
> 
> then clicking full config story then back up to the with footer story, the drawer displays... also seems to be same issue with the drawer--within-a-drawer-layout story as well

just verified this is in master branch too

**Comment by emclaug2** [comment]
@jeffvg Is this something that is happening when observed here? 
https://brightlayer-ui-components.github.io/angular/?path=/story/components-drawer--with-a-footer

Or is this just happening when you checkout the master branch locally and run it?

**Comment by jeffvg** [comment]
> @jeffvg Is this something that is happening when observed here? https://brightlayer-ui-components.github.io/angular/?path=/story/components-drawer--with-a-footer
> 
> Or is this just happening when you checkout the master branch locally and run it?

I see this in both master and feature branches

**Comment by emclaug2** [comment]
> I see this in both master and feature branches

Ok I'm doing a fresh clone and taking a look at the master branch now.

**Comment by emclaug2** [comment]
> Ok I'm doing a fresh clone and taking a look at the master branch now.

Looks like a small changedetection error introduced by the navigation depth management logic; I'll put add a small patch in a separate PR.  We'll have to verify the component isn't destroyed before attempting a cd.detectChanges.

**Comment by emclaug2** [comment]
@jeffvg I've added a bug fix in #398 which should get merged in & published before this PR.

**Review by jeffvg — APPROVED** [review]
ok looks good, no storybook error and showcase running on NG13

**Pull request merged**
