### PR TITLE
Feature/3551 clean up

### PR DESCRIPTION
**Pull request by emclaug2**
##### Overall
- Add favicon
- Remove the Home Screen & automatically redirect to the first component in the list (App Bar)
- Persist Active Tab between page changes
- Change Code block highlighting styles (normal and hrefs)

##### API Pages
- Replace Channel Value component picture on README
- Only show Drawer API docs (as opposed to Drawer, DrawerLayout, DrawerHeader, ...) while on the Drawer page.
- Update all MD docs to add single-quotes are string types (e.g `'dots'`, `'text'`, etc)

##### Examples
- Gracefully handle code block overflows on the examples page
- Round the codeblock and example container corners (4px)
- Fix content appearing underneath the Mat Tab Header when scrolling on Mobile Devices

##### Playground
- Add a Drawer Nav Item under DrawerSubheader playground example 
- Fix DrawerSubheader divider description
- Make long knob names on the playground wrap onto 2 lines (e.g. Drawer Playground `disableActivePlaygroundStyles` knob)
- Add Left & Right content knobs for Info List Item playground
- Change default Scorecard playground badge offset value
- Update ThreeLiner playground generated code to handle empty strings for title, subtitle, info
- Fix Color knob & Number knob not updating value (in input field) on change.

### CODE REVIEW

**Comment by emclaug2** [comment]
https://github.com/firebase/firebase-tools/issues/5071

**Comment by emclaug2** [comment]
This should be the final PR before the angular dev docs are ready for release - anything that seems off & should be fixed before release comment it here.

**Comment by jeffvg** [comment]
did the color knob fix get checked in? 
setting drawer header to warn is placed in code snippet but is not set
https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/drawer/header/playground

setting the info list item status color not updated in the input
https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/info-list-item/playground

list item tag color picker not set to defaults 
https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/list-item-tag/playground

**Comment by jeffvg** [comment]
one typo didn't make it in for empty state example doc "Customing the Title and Description" 
https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/empty-state/examples

**Comment by emclaug2** [comment]
> list item tag color picker not set to defaults https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/list-item-tag/playground

I've fixed the color input should it should now be responsive.
The ListItemTag doesn't really have component-level defaults; these values are provided by the theme so I've left the knobs (and input props) undefined  by default.

**Comment by huayunh** [comment]
the API table feels very condensed. The `padding` got overridden

**Comment by huayunh** [comment]
scorecard playground, this line's indentation is missing one space

image

**Comment by huayunh** [comment]
User menu API Doc, the Default value of this input is styled awkwardly

image

**Comment by huayunh** [comment]
Channel Value, API Docs, this needs to be monospaced
image

**Comment by huayunh** [comment]
"Spacer with Flex" story, consider setting the `flex` of the second rect to `2`, and the third rect to `3`, to be consistent with the numbers labeled inside the square (and match [React](https://brightlayer-ui-components.github.io/react-dev/components/spacer/examples))

**Comment by huayunh** [comment]
(I really have not much to say here; I think the current ng dev doc looks fantastic and had to be extra picky to get those comments above)

**Comment by emclaug2** [comment]
Thanks for the comments @huayunh & @jeffvg  - all points should be addressed now 👍

**Comment by jeffvg** [comment]
> did the color knob fix get checked in? setting drawer header to warn is placed in code snippet but is not set https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/drawer/header/playground
> 
> setting the info list item status color not updated in the input https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/info-list-item/playground
> 
> list item tag color picker not set to defaults https://blui-angular-docs--pr524-feature-3551-clean-u-q4yzcu0t.web.app/components/list-item-tag/playground

looks like this playground color needs updated from above comment....other than that this looks really awesome!

image

**Comment by emclaug2** [comment]
> looks like this playground color needs updated from above comment....other than that this looks really awesome!
> 
> image

This particular problem is at the component-level (possibly even the theme); we've logged an issue for this one a month ago:
https://github.com/brightlayer-ui/angular-component-library/issues/471

If preferred I can remove the knob until this issue is fixed.

**Review by jeffvg — APPROVED** [review]

**Comment by huayunh** [comment]
one small thing: the site drawer's activeItemShape shall be round

**Comment by emclaug2** [comment]
> one small thing: the site drawer's activeItemShape shall be round

Updated 🚀

**Comment by huayunh** [comment]
lets go

**Pull request merged**
