### PR TITLE
Add drawer playground

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add Drawer Playground

### CODE REVIEW

**Comment by ektasawant** [comment]
1. For smaller window size footer is content is breaking
Screenshot 2022-08-30 at 10 33 08 AM
2. `disableActiveItemParentStyles` is not removing styles of parent nav item
Screenshot 2022-08-30 at 10 34 39 AM
3. If I select a value from the slider and after removing the focus slider is still visible. And `openOnHoverDelay` doesn't work until you click on the drawer preview section.
Screenshot 2022-08-30 at 10 35 39 AM
3. In React `openOnHoverDelay` range is from 100 to 1000 and increased by 100ms. Do we need to match?

**Comment by emclaug2** [comment]
@ektasawant  
I've adjusted the slider to match React example's settings.

I've set up the slider so that after sliding it, it doesn't automatically dismiss from the screen; there is still a manual click outside of the slider required to dismiss it.  @huayunh is this behavior acceptable?

`disableActiveItemParentStyles` is working but not immediately - if you change this value it'll require a new item to be selected.

I've fixed the DrawerFooter issue in the Drawer playground.

**Comment by ektasawant** [comment]
> @ektasawant I've adjusted the slider to match React example's settings.
> 
> I've set up the slider so that after sliding it, it doesn't automatically dismiss from the screen; there is still a manual click outside of the slider required to dismiss it. @huayunh is this behavior acceptable?
> 
> `disableActiveItemParentStyles` is working but not immediately - if you change this value it'll require a new item to be selected.
> 
> I've fixed the DrawerFooter issue in the Drawer playground.

working fine 👍

**Comment by huayunh** [comment]
- [x] 1. The current slider works well
- [ ] 2. Can we make drawer nav item dividers to be false by default?
- [ ] 3. Since this playground is meant to show Drawer not Drawer Nav Item... can you make drawer nav item as simple as possible? That is, only icons and titles. No status stripes, no subtitles, (no dividers), less drawer items, only one nav group without title

Question
- Are you planning to make Drawer Layout its own page, or are you going to demonstrate drawer variants in the Drawer playground?

**Comment by emclaug2** [comment]
Thanks for the quick reviews @huayunh ; the Drawer example on the playground has been simplified.

The DrawerLayout is what controls the variants on the angular side so the variants can be found in the DrawerLayout PR.

**Review by huayunh — APPROVED** [review]
lgtm (didn't check the code)

One last comment is to organize your properties alphabetically within the same bucket

**Pull request merged**
