### PR TITLE
Add UserMenu playground

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add UserMenu Playground

### CODE REVIEW

**Comment by jeffvg** [comment]
nice!

image

**Review by huayunh — APPROVED** [review]
I like how `open` is controlled by both the component and the sidesheet

**Comment by jeffvg** [comment]
any reason to have these included in playground or too much?

image

**Comment by emclaug2** [comment]
> any reason to have these included in playground or too much?

I'll add these in under "Other" props since they're used to create the `positions` prop and not a direct prop.

**Comment by emclaug2** [comment]
Ok so there's a limitation on the angular side; we can add position-knobs so that the demo is updated, but cannot update the generated code.  The `positions` prop requires a new instance of a `ConnectionPositionPair` which can't be done in the template. 

People looking at the codes will have to refer to our code or API docs instead to see _how_ these `originX`, `originY`, etc knobs are used.

**Comment by huayunh** [comment]
hmm... if that's the case, I would leave it out of the playground. I have not run into any situations where someone **has** to change the menu `position`. If you have to showcase how to pass that property / attribute, I recommend doing it on the examples page

**Comment by emclaug2** [comment]
> hmm... if that's the case, I would leave it out of the playground. I have not run into any situations where someone **has** to change the menu `position`. If you have to showcase how to pass that property / attribute, I recommend doing it on the examples page

We've added a Placement example on the Examples page but it's def not interactive.  I'll comment out the placement knobs on the playground page and we can re-add if desired in the future.

**Review by jeffvg — APPROVED** [review]
looks good, just remember to comment out the position knobs or remove

**Pull request merged**
