### PR TITLE
Fix Bottom Sheet Not Rendering Content

### LINKED ISSUE #345: User Menu Bottomsheet Content not Rendering Correctly
#### Describe the bug
Dismissing the bottomsheet and recalling it before completely dismissed causes bottomsheet content to not render on screen. 

#### What is the expected behavior?
Bottomsheet content should render correctly every time.

#### What are the steps to reproduce?
1. Go to showcase
2. Make it a mobile view
3. Click usermenu, trigger bottomsheet
4. Quickly click twice to dismiss and re-trigger bottom sheet

#### Screenshots or links to minimum reproduction example
triple-click

#### Environment

Windows, Chrome
		
#### Anything else to add?
No

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #345 

#### Changes proposed in this Pull Request:
- Track whenever the user menu bottom sheet is being dismissed; ignore subsequent open requests until dismissed

#### To Test:
- Open storybook and rapidly click user menu on small viewport. 

Rapid clicking

### CODE REVIEW

**Comment by jeffvg** [comment]
looks good in storybook, fixed the odd behavior. Is this in showcase as well? I was unable to run showcase in the branch

**Comment by emclaug2** [comment]
> looks good in storybook, fixed the odd behavior. Is this in showcase as well? I was unable to run showcase in the branch

`yarn start:showcase` isn't working for you?

**Review by daileytj — APPROVED** [review]
Looks good to me!

**Comment by jeffvg** [comment]
> > looks good in storybook, fixed the odd behavior. Is this in showcase as well? I was unable to run showcase in the branch
> 
> `yarn start:showcase` isn't working for you?

had to clone again, showcase ran this time....

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
