### PR TITLE
Ready to publish

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Get ready to publish

### CODE REVIEW

**Comment by emclaug2** [comment]
I've changed this to a draft since there's an issue using the beta package on the showcase app.

**Comment by emclaug2** [comment]
The showcase issue has been addressed; the issue was caused by the DrawerState not being shared correctly between the DrawerLayout & Drawer.  This was because the DrawerLayout in the showcase didn't have direct access to the Drawer child due to the Drawer being wrapped in another component.  I've added in some more logic around #472 to handle this scenario in the future.

**Comment by jeffvg** [comment]
didn't we have drawer-body example? or just API doc...?

NG - 
https://blui-angular-docs--pr536-feature-publish-lvuh51ir.web.app/components/drawer/body/api-docs

REACT - 
https://blui-react-docs--pr623-feature-3552-final-f-mn1pd67j.web.app/components/drawer-body/examples

**Review by jeffvg — APPROVED** [review]
looks awesome

**Comment by emclaug2** [comment]
> didn't we have drawer-body example? or just API doc...?
> 
> NG - https://blui-angular-docs--pr536-feature-publish-lvuh51ir.web.app/components/drawer/body/api-docs
> 
> REACT - https://blui-react-docs--pr623-feature-3552-final-f-mn1pd67j.web.app/components/drawer-body/examples

On the angular side we don't have a Drawer Body examples page since it doesn't do anything that isn't captured in the other drawer subsection examples.  React has inheritable props which apply to the DrawerBody so it gets a little more attention.

**Pull request merged**
