### PR TITLE
Add header examples

### PR DESCRIPTION
**Pull request by emclaug2**
### Changes proposed in this Pull Request:
- Drawer Header Examples Page

### CODE REVIEW

**Comment by huayunh** [comment]
1. Can you do the line-highlighting for the line where the header appears
2. Are `<blui-drawer-header>`s supposed to be in `<blui-drawer-body>`s?
3. Is it possible to add more room here:
image
Like this:
image

**Comment by huayunh** [comment]
Now that you have the examples, please take this out of the `API Docs` page
image

**Comment by emclaug2** [comment]
Thanks @huayunh , PR has been updated.

**Comment by huayunh** [comment]
There are two more bullets in my first comment that you may want to attend to

**Comment by emclaug2** [comment]
> There are two more bullets in my first comment that you may want to attend to

Oops, I missed those ones.  Good catch on the drawer-header being in the drawer-body.  That's fixed.
I've also added line-highlighting but not in love with how it looks right now.

**Comment by huayunh** [comment]
want to take out those line numbers too? They've always felt strange to me.

**Comment by emclaug2** [comment]
> want to take out those line numbers too? They've always felt strange to me. I personally like the line highlighting, as it guides attention better

You got it, this is already looking a lot better.

**Comment by huayunh** [comment]
you have my design thumbs up! 

I didn't check the code... I don't Angular.

**Comment by ektasawant** [comment]
Changes looks fine 👍 .

Can we add space between example and code block?
Screenshot 2022-07-28 at 2 37 32 PM

**Review by ektasawant — APPROVED** [review]

**Pull request merged**
