### PR TITLE
Adjust script to nuke .git file if package.json doesnt exist

### LINKED ISSUE #317: Showcase Initialization Issue
#### Describe the bug
Cloning fresh repo & running storybook before showcase causes showcase to not initialize. 

#### What is the expected behavior?
Our initialization script should be smart enough to initialize the showcase folder even when the folder isn't empty.
This is because after the start:storybook command is ran, the showcase folder is no longer empty (?).  The command fails because the showcase folder is not empty by the time initialization occurs. 

#### What are the steps to reproduce?
1.  Clone the repo
2. Run `yarn start:storybook`
3. Run `yarn start:showcase` & see error. 

#### Environment

Windows		

#### Anything else to add?
Possible solution:  Run a command to empty the node_modules folder before attempting to initialize if the folder is not empty.

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #317 

#### Changes proposed in this Pull Request:
- Add a `rm .git` step to the initialization script if `package.json` not found.
- This step completely resets the demos/showcase folder & allows initialization to happen as if the folder was empty.

#### To Test:
- Clone repo, `yarn start:storybook` then run `yarn start:showcase`.

### CODE REVIEW

**Comment by emclaug2** [comment]
@ektasawant Can you try this again? I edited the nuke logic a bit:  If no package.json in showcase folder, remove all files in folder & attempt initialization.

**Comment by ektasawant** [comment]
It is working now 👍 . 
Screenshot 2022-01-07 at 5 30 46 PM

**Comment by emclaug2** [comment]
If this fix looks good I'll make small PRs for React & RN comp lib too if they need this change applied.

**Review by daileytj — APPROVED** [review]
Interesting... didn't even know this was an issue. Looks good now though.

**Comment by jeffvg** [comment]
I know this is merged now but not sure I understand why we had to do this.
On fresh clone and running yarn start:showcase does not run. Showcase only runs if storybook has run first?

After getting the showcase running, I deleted the package.json file and ran yarn start:showcase again.
I see the "Emptying Showcase Folder" in the terminal but I don't see the actual .git file get removed..

image

Am I not doing something correct?

**Comment by emclaug2** [comment]
> I know this is merged now but not sure I understand why we had to do this. On fresh clone and running yarn start:showcase does not run. Showcase only runs if storybook has run first?
> 
> After getting the showcase running, I deleted the package.json file and ran yarn start:showcase again. I see the "Emptying Showcase Folder" in the terminal but I don't see the actual .git file get removed..

> Am I not doing something correct?

I'll take a look with a fresh clone & `yarn start:showcase` right now.

**Pull request merged**
