### PR TITLE
Feature/3435 drawer layout

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Drawer Layout examples & playground

### CODE REVIEW

**Comment by huayunh** [comment]
Um... am I supposed to look at something for this draft PR?

**Comment by emclaug2** [comment]
> Um... am I supposed to look at something for this draft PR?

This is a little weird of a situation because I've got 3 PRs.

[Release] <- [Figma Updates] <- [Drawer Playground] <- [DrawerLayout Examples/Playground].

If you want to leave some comments on this one I won't be opposed, but it's a lower priority.

**Comment by daileytj** [comment]
Screen Shot 2022-09-06 at 12 45 42 PM
Should these list items have a hover state? If so, can we fix the padding here so the hover background color fills the width of the side-drawer.

**Review by daileytj — APPROVED** [review]
Inputs and dynamic code generation looks fine, just see my comments on some potential style issues. Feel free to address them in separate issues if you want to.

**Comment by huayunh** [comment]
1. Temporary drawer, the distance between the hamburger menu icon and the title needs to be larger. This applies to both the example and what you have in the playground
2. Temporary drawer, when the drawer is expanded, can we make the top-left corner a close icon?
3. Persistent Variant example, there's a weird padding on the top
4. Playground, rail variant, I can still see Tooltips when `disableRailTooltip` is enabled
5. Rail Variant example (regular, not condensed), I suggest adding dividers between rail items by default
6. Playground at a smaller viewport should NOT bleed into that side sheet

**Comment by emclaug2** [comment]
> 1. Temporary drawer, the distance between the hamburger menu icon and the title needs to be larger. This applies to both the example and what you have in the playground

I've increased the distance a bit.

> 2. Temporary drawer, when the drawer is expanded, can we make the top-left corner a close icon?

You got it.

> 3. Persistent Variant example, there's a weird padding on the top of the code snippet

That's been removed.

> 4. Playground, rail variant, I can still see Tooltips when `disableRailTooltip` is enabled

That's the html `title` prop showing up - the real tooltip is there but hard to see. Fortunately the `disableRailTooltip` prop works. 

> 5. Rail Variant example (regular, not condensed), I suggest adding dividers between rail items by default

You got it. 

> 6. Playground at a smaller viewport should NOT bleed into that side sheet

This is updated now for better mobile responsiveness.

**Comment by huayunh** [comment]
> I've increased the distance a bit.

You may want to check the implementation against the distance specified on docit design spec: https://brightlayer-ui-dev.github.io/patterns/appbar#design-specifications

**Pull request merged**
