### PR TITLE
Feature/pr tweaks

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Adjust nav item section titles 
-  Add basic example for drawer footer
-  Add code highlighting for nav item examples
-  Drawer anatomy as a list

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]
looks really good

**Comment by huayunh** [comment]
background color?

**Comment by huayunh** [comment]
Other than that, can verify everything is good to go. Didn't check the code.

**Comment by emclaug2** [comment]
> background color?

Hey can you remind me what needs to change? Is it just the README tab background color?  And also what color should it be?

**Comment by huayunh** [comment]
Yeah, I think both example and API Doc should have a default background color of white50. Playground shall stay white200

**Comment by emclaug2** [comment]
I've updated the theme for all 3 tabs but since the playground is still a WIP we can adjust it later.

**Pull request merged**
