### PR TITLE
Feature/sample examples page

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- There isn't a formal story for this - I'd treat this as an expansion of the scaffolding story that was already merged in.
- This adds a small Example page for ListItemTag that experiments with showing/hiding code snippets, syntax/line highlights & how to organize components. 

#### To Test:
- https://pxblue-temp.web.app/list-item-tag

### CODE REVIEW

**Comment by emclaug2** [comment]
@daileytj @jeffvg This PR will keep growing if it doesn't get merged in soon, I'd probably just treat this as an extension of the scaffolding story.  We can tweak how it looks at part of smaller follow-up PRs.

**Comment by daileytj** [comment]
Fair enough. I'll approve it, but just a few things.

Should the tabs be part of the max-width content? Not sure if this was addressed in the design phase.
Screen Shot 2022-07-22 at 2 43 42 PM

I believe we have a bug on the react side for this issue, but should the drawer parent item open when you refresh or use a deep link. For example: https://pxblue-temp.web.app/drawer/nav-item?tab=example doesn't open the parent dropdown to expose the selected route.

**Review by daileytj — APPROVED** [review]

**Comment by emclaug2** [comment]
@daileytj  Thank you, Tom - appreciate it. Have a great weekend :)

**Comment by emclaug2** [comment]
> Should the tabs be part of the max-width content? Not sure if this was addressed in the design phase. Screen Shot 2022-07-22 at 2 43 42 PM

For the tabs, I've got another branch going that slightly changes the tab styles to be closer to the figma design.  I'll make a PR for this on Monday. 

> I believe we have a bug on the react side for this issue, but should the drawer parent item open when you refresh or use a deep link. For example: https://pxblue-temp.web.app/drawer/nav-item?tab=example doesn't open the parent dropdown to expose the selected route.

This is def a bug & I'll patch it up soon, thanks for catching this.

**Pull request merged**
