### PR TITLE
Feature/3386 header playground

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add Playground for Drawer Header

### CODE REVIEW

**Comment by emclaug2** [comment]
`color` prop does not work, made an issue for it here: https://github.com/brightlayer-ui/angular-component-library/issues/471

**Review by jeffvg — APPROVED** [review]
looks good, covering all options

**Comment by huayunh** [comment]
If an input is optional, please do this for the dropdown, instead of leaving it blank. I have added this to the Figma side.

image

**Comment by huayunh** [comment]
I also have a mixed feeling to the "Show Title Content" option. I am more inclined toward removing it, since we've already shown that on the examples page.

**Comment by ektasawant** [comment]
Changes looks good only agree with https://github.com/brightlayer-ui/angular-component-library/pull/470#issuecomment-1206625297.

**Comment by emclaug2** [comment]
> I also have a mixed feeling to the "Show Title Content" option. I am more inclined toward removing it, since we've already shown that on the examples page.

I'm happy to remove it considering it's on the examples page already.

**Comment by huayunh** [comment]
https://user-images.githubusercontent.com/8997218/183415511-ee6a42ed-f8bf-48a7-bf6a-b720929ea27a.mov

I just noticed this — I am not sure if this is part of the Angular component library or part of this playground.

**Comment by huayunh** [comment]
For the dropdown, I also encourage the use of a divider and have the  "*(Empty)*" option listed on the top.

**Comment by emclaug2** [comment]
> For the dropdown, I also encourage the use of a divider and have the "_(Empty)_" option listed on the top.

I've just pushed out the updated styles for the select menu - it might look a little bit off because the default choice isn't the first option in the list but the divider is there. 👍

**Comment by huayunh** [comment]
that icon issue can still be reproduced this way after a hard reload:
- turn off `Show Icon`
- change to a different color
- turn on `Show Icon`

https://user-images.githubusercontent.com/8997218/183460598-82a38862-452f-4034-b0b9-c73055f5c60b.mov

**Comment by jeffvg** [comment]
I didn't check this since I looked before but is
color prop does not work, made an issue for it here: https://github.com/brightlayer-ui/angular-component-library/issues/471

**Comment by emclaug2** [comment]
> I didn't check this since I looked before but is fixed now? color prop does not work, made an issue for it here: #471

I still see this as broken.

**Comment by emclaug2** [comment]
> that icon issue can still be reproduced this way after a hard reload:
> 
> * turn off `Show Icon`
> * change to a different color
> * turn on `Show Icon`

Thanks @huayunh  - this was an issue with the DrawerHeader component.  I've made an issue for it & patched it since it was a one-liner.

**Comment by emclaug2** [comment]
I'll merge this in now seeing that all the comments have been addressed.  If there's anything else we can address it in the next PR - subheader.

**Pull request merged**
