### PR TITLE
Feature/3387 drawer subheader playground

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Drawer Subheader Demo & Drawer Footer Demo (they are very similar)
- This demo is not very good right now.  A stand-alone drawer is not able to open & close elegantly.  I've made an issue for this.  I can fix this issue as part of this PR if need be.

### CODE REVIEW

**Comment by huayunh** [comment]
Hmm...

1. Can you add a few dummy drawer nav items? It is really hard to see that bottom divider.
2. Is it even possible to make the drawer collapse? We are trying to showcase "hideContentOnCollapse", but the drawer doesn't actually collapse. Although if that makes the drawer overly complicated then we shall scrap that idea.

**Comment by emclaug2** [comment]
> 2. Is it even possible to make the drawer collapse?

This is a little tricky, the answer is yes but it'll involve slightly modifying the component lib.   It would be easier to make this change & test to see if everything is still working if we had the DrawerLayout examples page & sandbox available. 

I can make this change tomorrow morning & get a stand-alone drawer to open/close.

**Comment by huayunh** [comment]
I see. We can also consider not doing the playground at all, given that there are only two inputs and both are fairly straightforward.

**Comment by emclaug2** [comment]
I'd still want to do the playground because it's useful for catching some bugs, like for instance the footer divider goes away whenever the drawer is closed, even with the `hideContentOnCollapse` prop as false.  I'd expect it to be true.  

This sandbox will be a lot more interesting if the drawer can open and close.  I can also add a button for `Open Drawer` in case people don't click the example.

**Comment by huayunh** [comment]
Sounds good. If that becomes too big of a challenge, this is acceptable with me too. The focus here should be about the subheader, not about the drawer state.

image

**Comment by emclaug2** [comment]
I've updated the Footer & Subheader examples to open/close on menu click.  This PR now fixes #472 as well.

**Review by huayunh — APPROVED** [review]
Looks good to me. (didn't check the code)

**Pull request merged**
